PREFIX foaf: <http://xmlns.com/foaf/0.1/>
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/accounts/deltas> {
     <http://data.lblod.info/foaf/account/id/f6f1df05-02c0-48bc-b4ee-774b96e2fb43> a foaf:OnlineAccount.

     <http://data.lblod.info/foaf/agent/id/bd3c9de2-5641-47ac-8a79-f327262119d8> a foaf:Agent;
         foaf:account <http://data.lblod.info/foaf/account/id/f6f1df05-02c0-48bc-b4ee-774b96e2fb43>.

     <http://data.lblod.info/foaf/group/id/25e40ddc-0532-435d-a13f-7a2877cde5a7> a foaf:Group;
       foaf:member <http://data.lblod.info/foaf/agent/id/bd3c9de2-5641-47ac-8a79-f327262119d8>;
       foaf:name "verenigingen".
  }
}